/* Double-to-string conversion adapted for tinypy from Ulf Adams' Ryu
 * algorithm at commit 4c0618b0e44f7ef027ebae05d2cc7812048f7c8f.
 * Copyright 2018 Ulf Adams.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. */

#include "internal.h"

#include <string.h>

#include "double_conversion_common.h"
#include "generated/double_conversion_digits.h"
#include "double_conversion_intrinsics.h"

#include "generated/double_conversion_table.h"

#define TINYPY_DOUBLE_MANTISSA_BITS 52
#define TINYPY_DOUBLE_EXPONENT_BITS 11
#define TINYPY_DOUBLE_BIAS 1023

static inline uint32_t __tinypy_double_decimal_length(const uint64_t v) {
    // This is slightly faster than a loop.
    // The average output length is 16.38 digits, so we check high-to-low.
    // Function precondition: v is not an 18, 19, or 20-digit number.
    // (17 digits are sufficient for round-tripping.)
    if (v >= 10000000000000000L) {
        return 17;
    }
    if (v >= 1000000000000000L) {
        return 16;
    }
    if (v >= 100000000000000L) {
        return 15;
    }
    if (v >= 10000000000000L) {
        return 14;
    }
    if (v >= 1000000000000L) {
        return 13;
    }
    if (v >= 100000000000L) {
        return 12;
    }
    if (v >= 10000000000L) {
        return 11;
    }
    if (v >= 1000000000L) {
        return 10;
    }
    if (v >= 100000000L) {
        return 9;
    }
    if (v >= 10000000L) {
        return 8;
    }
    if (v >= 1000000L) {
        return 7;
    }
    if (v >= 100000L) {
        return 6;
    }
    if (v >= 10000L) {
        return 5;
    }
    if (v >= 1000L) {
        return 4;
    }
    if (v >= 100L) {
        return 3;
    }
    if (v >= 10L) {
        return 2;
    }
    return 1;
}

// A floating decimal representing m * 10^e.
typedef struct tinypy_double_decimal_t {
    uint64_t mantissa;
    // Decimal exponent's range is -324 to 308
    // inclusive, and can fit in a short if needed.
    int32_t exponent;
} tinypy_double_decimal_t;

static inline tinypy_double_decimal_t __tinypy_double_to_decimal(const uint64_t ieeeMantissa, const uint32_t ieeeExponent) {
    int32_t e2;
    uint64_t m2;
    if (ieeeExponent == 0) {
        // We subtract 2 so that the bounds computation has 2 additional bits.
        e2 = 1 - TINYPY_DOUBLE_BIAS - TINYPY_DOUBLE_MANTISSA_BITS - 2;
        m2 = ieeeMantissa;
    } else {
        e2 = (int32_t)ieeeExponent - TINYPY_DOUBLE_BIAS - TINYPY_DOUBLE_MANTISSA_BITS - 2;
        m2 = (1ull << TINYPY_DOUBLE_MANTISSA_BITS) | ieeeMantissa;
    }
    const tinypy_bool_t even = (m2 & 1) == 0;
    const tinypy_bool_t acceptBounds = even;

    // Step 2: Determine the interval of valid decimal representations.
    const uint64_t mv = 4 * m2;
    // Implicit tinypy_bool_t -> int conversion. True is 1, TINYPY_FALSE is 0.
    const uint32_t mmShift = ieeeMantissa != 0 || ieeeExponent <= 1;
    // We would compute mp and mm like this:
    // uint64_t mp = 4 * m2 + 2;
    // uint64_t mm = mv - 1 - mmShift;

    // Step 3: Convert to a decimal power base using 128-bit arithmetic.
    uint64_t vr, vp, vm;
    int32_t e10;
    tinypy_bool_t vmIsTrailingZeros = TINYPY_FALSE;
    tinypy_bool_t vrIsTrailingZeros = TINYPY_FALSE;
    if (e2 >= 0) {
        // I tried special-casing q == 0, but there was no effect on performance.
        // This expression is slightly faster than max(0, __tinypy_double_log10_power_of_two(e2) - 1).
        const uint32_t q = __tinypy_double_log10_power_of_two(e2) - (e2 > 3);
        e10 = (int32_t)q;
        const int32_t k = TINYPY_DOUBLE_POWER_OF_FIVE_INVERSE_BIT_COUNT + __tinypy_double_power_of_five_bits((int32_t)q) - 1;
        const int32_t i = -e2 + (int32_t)q + k;
        vr = __tinypy_double_multiply_shift_all(m2, __tinypy_double_power_of_five_inverse_split[q], i, &vp, &vm, mmShift);
        if (q <= 21) {
            // This should use q <= 22, but I think 21 is also safe. Smaller values
            // may still be safe, but it's more difficult to reason about them.
            // Only one of mp, mv, and mm can be a multiple of 5, if any.
            const uint32_t mvMod5 = ((uint32_t)mv) - 5 * ((uint32_t)__tinypy_double_divide_5(mv));
            if (mvMod5 == 0) {
                vrIsTrailingZeros = __tinypy_double_multiple_of_power_of_five(mv, q);
            } else if (acceptBounds) {
                // Same as min(e2 + (~mm & 1), pow5Factor(mm)) >= q
                // <=> e2 + (~mm & 1) >= q && pow5Factor(mm) >= q
                // <=> TINYPY_TRUE && pow5Factor(mm) >= q, since e2 >= q.
                vmIsTrailingZeros = __tinypy_double_multiple_of_power_of_five(mv - 1 - mmShift, q);
            } else {
                // Same as min(e2 + 1, pow5Factor(mp)) >= q.
                vp -= __tinypy_double_multiple_of_power_of_five(mv + 2, q);
            }
        }
    } else {
        // This expression is slightly faster than max(0, __tinypy_double_log10_power_of_five(-e2) - 1).
        const uint32_t q = __tinypy_double_log10_power_of_five(-e2) - (-e2 > 1);
        e10 = (int32_t)q + e2;
        const int32_t i = -e2 - (int32_t)q;
        const int32_t k = __tinypy_double_power_of_five_bits(i) - TINYPY_DOUBLE_POWER_OF_FIVE_BIT_COUNT;
        const int32_t j = (int32_t)q - k;
        vr = __tinypy_double_multiply_shift_all(m2, __tinypy_double_power_of_five_split[i], j, &vp, &vm, mmShift);
        if (q <= 1) {
            // {vr,vp,vm} is trailing zeros if {mv,mp,mm} has at least q trailing 0 bits.
            // mv = 4 * m2, so it always has at least two trailing 0 bits.
            vrIsTrailingZeros = TINYPY_TRUE;
            if (acceptBounds) {
                // mm = mv - 1 - mmShift, so it has 1 trailing 0 bit iff mmShift == 1.
                vmIsTrailingZeros = mmShift == 1;
            } else {
                // mp = mv + 2, so it always has at least one trailing 0 bit.
                --vp;
            }
        } else if (q < 63) { // TODO(ulfjack): Use a tighter bound here.
            // We want to know if the full product has at least q trailing zeros.
            // We need to compute min(p2(mv), p5(mv) - e2) >= q
            // <=> p2(mv) >= q && p5(mv) - e2 >= q
            // <=> p2(mv) >= q (because -e2 >= q)
            vrIsTrailingZeros = __tinypy_double_multiple_of_power_of_two(mv, q);
        }
    }

    // Step 4: Find the shortest decimal representation in the interval of valid representations.
    int32_t removed = 0;
    uint8_t lastRemovedDigit = 0;
    uint64_t output;
    // On average, we remove ~2 digits.
    if (vmIsTrailingZeros || vrIsTrailingZeros) {
        // General case, which happens rarely (~0.7%).
        for (;;) {
            const uint64_t vpDiv10 = __tinypy_double_divide_10(vp);
            const uint64_t vmDiv10 = __tinypy_double_divide_10(vm);
            if (vpDiv10 <= vmDiv10) {
                break;
            }
            const uint32_t vmMod10 = ((uint32_t)vm) - 10 * ((uint32_t)vmDiv10);
            const uint64_t vrDiv10 = __tinypy_double_divide_10(vr);
            const uint32_t vrMod10 = ((uint32_t)vr) - 10 * ((uint32_t)vrDiv10);
            vmIsTrailingZeros &= vmMod10 == 0;
            vrIsTrailingZeros &= lastRemovedDigit == 0;
            lastRemovedDigit = (uint8_t)vrMod10;
            vr = vrDiv10;
            vp = vpDiv10;
            vm = vmDiv10;
            ++removed;
        }
        if (vmIsTrailingZeros) {
            for (;;) {
                const uint64_t vmDiv10 = __tinypy_double_divide_10(vm);
                const uint32_t vmMod10 = ((uint32_t)vm) - 10 * ((uint32_t)vmDiv10);
                if (vmMod10 != 0) {
                    break;
                }
                const uint64_t vpDiv10 = __tinypy_double_divide_10(vp);
                const uint64_t vrDiv10 = __tinypy_double_divide_10(vr);
                const uint32_t vrMod10 = ((uint32_t)vr) - 10 * ((uint32_t)vrDiv10);
                vrIsTrailingZeros &= lastRemovedDigit == 0;
                lastRemovedDigit = (uint8_t)vrMod10;
                vr = vrDiv10;
                vp = vpDiv10;
                vm = vmDiv10;
                ++removed;
            }
        }
        if (vrIsTrailingZeros && lastRemovedDigit == 5 && vr % 2 == 0) {
            // Round even if the exact number is .....50..0.
            lastRemovedDigit = 4;
        }
        // We need to take vr + 1 if vr is outside bounds or we need to round up.
        output = vr + ((vr == vm && (!acceptBounds || !vmIsTrailingZeros)) || lastRemovedDigit >= 5);
    } else {
        // Specialized for the common case (~99.3%). Percentages below are relative to this.
        tinypy_bool_t roundUp = TINYPY_FALSE;
        const uint64_t vpDiv100 = __tinypy_double_divide_100(vp);
        const uint64_t vmDiv100 = __tinypy_double_divide_100(vm);
        if (vpDiv100 > vmDiv100) { // Optimization: remove two digits at a time (~86.2%).
            const uint64_t vrDiv100 = __tinypy_double_divide_100(vr);
            const uint32_t vrMod100 = ((uint32_t)vr) - 100 * ((uint32_t)vrDiv100);
            roundUp = vrMod100 >= 50;
            vr = vrDiv100;
            vp = vpDiv100;
            vm = vmDiv100;
            removed += 2;
        }
        // Loop iterations below (approximately), without optimization above:
        // 0: 0.03%, 1: 13.8%, 2: 70.6%, 3: 14.0%, 4: 1.40%, 5: 0.14%, 6+: 0.02%
        // Loop iterations below (approximately), with optimization above:
        // 0: 70.6%, 1: 27.8%, 2: 1.40%, 3: 0.14%, 4+: 0.02%
        for (;;) {
            const uint64_t vpDiv10 = __tinypy_double_divide_10(vp);
            const uint64_t vmDiv10 = __tinypy_double_divide_10(vm);
            if (vpDiv10 <= vmDiv10) {
                break;
            }
            const uint64_t vrDiv10 = __tinypy_double_divide_10(vr);
            const uint32_t vrMod10 = ((uint32_t)vr) - 10 * ((uint32_t)vrDiv10);
            roundUp = vrMod10 >= 5;
            vr = vrDiv10;
            vp = vpDiv10;
            vm = vmDiv10;
            ++removed;
        }
        // We need to take vr + 1 if vr is outside bounds or we need to round up.
        output = vr + (vr == vm || roundUp);
    }
    const int32_t exp = e10 + removed;

    tinypy_double_decimal_t fd;
    fd.exponent = exp;
    fd.mantissa = output;
    return fd;
}

static inline int32_t __tinypy_double_to_characters(const tinypy_double_decimal_t v, const tinypy_bool_t sign, char *const result) {
    // Step 5: Print the decimal representation.
    int32_t index = INT32_C(0);
    if (sign) {
        result[index++] = '-';
    }

    uint64_t output = v.mantissa;
    const uint32_t olength = __tinypy_double_decimal_length(output);

    // Print the decimal digits.
    // The following code is equivalent to:
    // for (uint32_t i = 0; i < olength - 1; ++i) {
    //   const uint32_t c = output % 10; output /= 10;
    //   result[index + olength - i] = (char) ('0' + c);
    // }
    // result[index] = '0' + output % 10;

    uint32_t i = 0;
    // We prefer 32-bit operations, even on 64-bit platforms.
    // We have at most 17 digits, and uint32_t can store 9 digits.
    // If output doesn't fit into uint32_t, we cut off 8 digits,
    // so the rest will fit into uint32_t.
    if ((output >> 32) != 0) {
        // Expensive 64-bit division.
        const uint64_t q = __tinypy_double_divide_100000000(output);
        uint32_t output2 = ((uint32_t)output) - 100000000 * ((uint32_t)q);
        output = q;

        const uint32_t c = output2 % 10000;
        output2 /= 10000;
        const uint32_t d = output2 % 10000;
        const uint32_t c0 = (c % 100) << 1;
        const uint32_t c1 = (c / 100) << 1;
        const uint32_t d0 = (d % 100) << 1;
        const uint32_t d1 = (d / 100) << 1;
        memcpy(result + index + olength - 1, __tinypy_double_digit_table + c0, 2);
        memcpy(result + index + olength - 3, __tinypy_double_digit_table + c1, 2);
        memcpy(result + index + olength - 5, __tinypy_double_digit_table + d0, 2);
        memcpy(result + index + olength - 7, __tinypy_double_digit_table + d1, 2);
        i += 8;
    }
    uint32_t output2 = (uint32_t)output;
    while (output2 >= 10000) {
#ifdef __clang__ // https://bugs.llvm.org/show_bug.cgi?id=38217
        const uint32_t c = output2 - 10000 * (output2 / 10000);
#else
        const uint32_t c = output2 % 10000;
#endif
        output2 /= 10000;
        const uint32_t c0 = (c % 100) << 1;
        const uint32_t c1 = (c / 100) << 1;
        memcpy(result + index + olength - i - 1, __tinypy_double_digit_table + c0, 2);
        memcpy(result + index + olength - i - 3, __tinypy_double_digit_table + c1, 2);
        i += 4;
    }
    if (output2 >= 100) {
        const uint32_t c = (output2 % 100) << 1;
        output2 /= 100;
        memcpy(result + index + olength - i - 1, __tinypy_double_digit_table + c, 2);
        i += 2;
    }
    if (output2 >= 10) {
        const uint32_t c = output2 << 1;
        // We can't use memcpy here: the decimal dot goes between these two digits.
        result[index + olength - i] = __tinypy_double_digit_table[c + 1];
        result[index] = __tinypy_double_digit_table[c];
    } else {
        result[index] = (char)('0' + output2);
    }

    // Print decimal point if needed.
    if (olength > 1) {
        result[index + 1] = '.';
        index += olength + 1;
    } else {
        ++index;
    }

    // Print the exponent.
    result[index++] = 'E';
    int32_t exp = v.exponent + (int32_t)olength - 1;
    if (exp < 0) {
        result[index++] = '-';
        exp = -exp;
    }

    if (exp >= 100) {
        const int32_t c = exp % 10;
        memcpy(result + index, __tinypy_double_digit_table + 2 * (exp / 10), 2);
        result[index + 2] = (char)('0' + c);
        index += 3;
    } else if (exp >= 10) {
        memcpy(result + index, __tinypy_double_digit_table + 2 * exp, 2);
        index += 2;
    } else {
        result[index++] = (char)('0' + exp);
    }

    return index;
}

static inline tinypy_bool_t __tinypy_double_small_integer(const uint64_t ieeeMantissa, const uint32_t ieeeExponent, tinypy_double_decimal_t *const v) {
    const uint64_t m2 = (1ull << TINYPY_DOUBLE_MANTISSA_BITS) | ieeeMantissa;
    const int32_t e2 = (int32_t)ieeeExponent - TINYPY_DOUBLE_BIAS - TINYPY_DOUBLE_MANTISSA_BITS;

    if (e2 > 0) {
        // f = m2 * 2^e2 >= 2^53 is an integer.
        // Ignore this case for now.
        return TINYPY_FALSE;
    }

    if (e2 < -52) {
        // f < 1.
        return TINYPY_FALSE;
    }

    // Since 2^52 <= m2 < 2^53 and 0 <= -e2 <= 52: 1 <= f = m2 / 2^-e2 < 2^53.
    // Test if the lower -e2 bits of the significand are 0, i.e. whether the fraction is 0.
    const uint64_t mask = (1ull << -e2) - 1;
    const uint64_t fraction = m2 & mask;
    if (fraction != 0) {
        return TINYPY_FALSE;
    }

    // f is an integer in the range [1, 2^53).
    // Note: mantissa might contain trailing (decimal) 0's.
    // Note: since 2^53 < 10^16, there is no need to adjust __tinypy_double_decimal_length().
    v->mantissa = m2 >> -e2;
    v->exponent = 0;
    return TINYPY_TRUE;
}

int32_t tinypy_internal_d2s_buffered_n(double f, char *result) {
    // Step 1: Decode the floating-point number, and unify normalized and subnormal cases.
    const uint64_t bits = __tinypy_double_to_bits(f);

    // Decode bits into sign, mantissa, and exponent.
    const tinypy_bool_t ieeeSign = ((bits >> (TINYPY_DOUBLE_MANTISSA_BITS + TINYPY_DOUBLE_EXPONENT_BITS)) & 1) != 0;
    const uint64_t ieeeMantissa = bits & ((1ull << TINYPY_DOUBLE_MANTISSA_BITS) - 1);
    const uint32_t ieeeExponent = (uint32_t)((bits >> TINYPY_DOUBLE_MANTISSA_BITS) & ((1u << TINYPY_DOUBLE_EXPONENT_BITS) - 1));
    // Case distinction; exit early for the easy cases.
    if (ieeeExponent == ((1u << TINYPY_DOUBLE_EXPONENT_BITS) - 1u) || (ieeeExponent == 0 && ieeeMantissa == 0)) {
        int32_t return_value_1 = __tinypy_double_copy_special(result, ieeeSign, ieeeExponent != 0U ? TINYPY_TRUE : TINYPY_FALSE, ieeeMantissa != UINT64_C(0) ? TINYPY_TRUE : TINYPY_FALSE);

        return return_value_1;
    }

    tinypy_double_decimal_t v;
    const tinypy_bool_t isSmallInt = __tinypy_double_small_integer(ieeeMantissa, ieeeExponent, &v);
    if (isSmallInt) {
        // For small integers in the range [1, 2^53), v.mantissa might contain trailing (decimal) zeros.
        // For scientific notation we need to move these zeros into the exponent.
        // (This is not needed for fixed-point notation, so it might be beneficial to trim
        // trailing zeros in __tinypy_double_to_characters only if needed - once fixed-point notation output is implemented.)
        for (;;) {
            const uint64_t q = __tinypy_double_divide_10(v.mantissa);
            const uint32_t r = ((uint32_t)v.mantissa) - 10 * ((uint32_t)q);
            if (r != 0) {
                break;
            }
            v.mantissa = q;
            ++v.exponent;
        }
    } else {
        v = __tinypy_double_to_decimal(ieeeMantissa, ieeeExponent);
    }

    int32_t return_value_2 = __tinypy_double_to_characters(v, ieeeSign, result);
    return return_value_2;
}
