#ifndef TINYPY_COMPILER_PARSER_ERROR_H
#define TINYPY_COMPILER_PARSER_ERROR_H

typedef enum tinypy_parser_result_e {
    TINYPY_PARSER_OK = 10,
    TINYPY_PARSER_EOF = 11,
    TINYPY_PARSER_INTERRUPTED = 12,
    TINYPY_PARSER_BAD_TOKEN = 13,
    TINYPY_PARSER_SYNTAX_ERROR = 14,
    TINYPY_PARSER_OUT_OF_MEMORY = 15,
    TINYPY_PARSER_DONE = 16,
    TINYPY_PARSER_EXECUTION_ERROR = 17,
    TINYPY_PARSER_TAB_SPACE_ERROR = 18,
    TINYPY_PARSER_OVERFLOW = 19,
    TINYPY_PARSER_TOO_DEEP = 20,
    TINYPY_PARSER_DEDENT_ERROR = 21,
    TINYPY_PARSER_DECODE_ERROR = 22,
    TINYPY_PARSER_EOF_TRIPLE_STRING = 23,
    TINYPY_PARSER_EOL_STRING = 24,
    TINYPY_PARSER_LINE_CONTINUATION_ERROR = 25,
    TINYPY_PARSER_IO_ERROR = 26
} tinypy_parser_result_e;

#endif
