#ifndef TINYPY_COMPILER_TOKEN_H
#define TINYPY_COMPILER_TOKEN_H

#include "tinypy/types.h"

typedef enum tinypy_token_type_e {
    TINYPY_TOKEN_END = 0,
    TINYPY_TOKEN_NAME = 1,
    TINYPY_TOKEN_NUMBER = 2,
    TINYPY_TOKEN_STRING = 3,
    TINYPY_TOKEN_NEWLINE = 4,
    TINYPY_TOKEN_INDENT = 5,
    TINYPY_TOKEN_DEDENT = 6,
    TINYPY_TOKEN_LEFT_PARENTHESIS = 7,
    TINYPY_TOKEN_RIGHT_PARENTHESIS = 8,
    TINYPY_TOKEN_LEFT_BRACKET = 9,
    TINYPY_TOKEN_RIGHT_BRACKET = 10,
    TINYPY_TOKEN_COLON = 11,
    TINYPY_TOKEN_COMMA = 12,
    TINYPY_TOKEN_SEMICOLON = 13,
    TINYPY_TOKEN_PLUS = 14,
    TINYPY_TOKEN_MINUS = 15,
    TINYPY_TOKEN_STAR = 16,
    TINYPY_TOKEN_SLASH = 17,
    TINYPY_TOKEN_VERTICAL_BAR = 18,
    TINYPY_TOKEN_AMPERSAND = 19,
    TINYPY_TOKEN_LESS = 20,
    TINYPY_TOKEN_GREATER = 21,
    TINYPY_TOKEN_EQUAL = 22,
    TINYPY_TOKEN_DOT = 23,
    TINYPY_TOKEN_PERCENT = 24,
    TINYPY_TOKEN_BACKQUOTE = 25,
    TINYPY_TOKEN_LEFT_BRACE = 26,
    TINYPY_TOKEN_RIGHT_BRACE = 27,
    TINYPY_TOKEN_EQUAL_EQUAL = 28,
    TINYPY_TOKEN_NOT_EQUAL = 29,
    TINYPY_TOKEN_LESS_EQUAL = 30,
    TINYPY_TOKEN_GREATER_EQUAL = 31,
    TINYPY_TOKEN_TILDE = 32,
    TINYPY_TOKEN_CIRCUMFLEX = 33,
    TINYPY_TOKEN_LEFT_SHIFT = 34,
    TINYPY_TOKEN_RIGHT_SHIFT = 35,
    TINYPY_TOKEN_DOUBLE_STAR = 36,
    TINYPY_TOKEN_PLUS_EQUAL = 37,
    TINYPY_TOKEN_MINUS_EQUAL = 38,
    TINYPY_TOKEN_STAR_EQUAL = 39,
    TINYPY_TOKEN_SLASH_EQUAL = 40,
    TINYPY_TOKEN_PERCENT_EQUAL = 41,
    TINYPY_TOKEN_AMPERSAND_EQUAL = 42,
    TINYPY_TOKEN_VERTICAL_BAR_EQUAL = 43,
    TINYPY_TOKEN_CIRCUMFLEX_EQUAL = 44,
    TINYPY_TOKEN_LEFT_SHIFT_EQUAL = 45,
    TINYPY_TOKEN_RIGHT_SHIFT_EQUAL = 46,
    TINYPY_TOKEN_DOUBLE_STAR_EQUAL = 47,
    TINYPY_TOKEN_DOUBLE_SLASH = 48,
    TINYPY_TOKEN_DOUBLE_SLASH_EQUAL = 49,
    TINYPY_TOKEN_AT = 50,
    TINYPY_TOKEN_OPERATOR = 51,
    TINYPY_TOKEN_ERROR = 52,
    TINYPY_TOKEN_COUNT = 53,
    TINYPY_TOKEN_NONTERMINAL_OFFSET = 256
} tinypy_token_type_e;

#define TINYPY_TOKEN_IS_TERMINAL(type) ((type) < TINYPY_TOKEN_NONTERMINAL_OFFSET)
#define TINYPY_TOKEN_IS_NONTERMINAL(type) ((type) >= TINYPY_TOKEN_NONTERMINAL_OFFSET)
#define TINYPY_TOKEN_IS_END(type) ((type) == TINYPY_TOKEN_END)

extern const char *const __tinypy_parser_token_names[];
int __tinypy_token_one_character(int first);
int __tinypy_token_two_characters(int first, int second);
int __tinypy_token_three_characters(int first, int second, int third);

#endif
